# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib mvregrp
#' @importFrom Rcpp evalCpp
NULL

#' @export
generateSymmetricMatrix <- function(offDiagonal, n) {
    .Call('_mvregrp_generateSymmetricMatrix', PACKAGE = 'mvregrp', offDiagonal, n)
}

#' @export
dmvnorm <- function(x, Sigma) {
    .Call('_mvregrp_dmvnorm', PACKAGE = 'mvregrp', x, Sigma)
}

#' @export
calc_loglik <- function(sh_len_g1_indices, sh_h_mapper, z_covs, z_sh_ind, Zbeta, VH_all, sigma2_v) {
    .Call('_mvregrp_calc_loglik', PACKAGE = 'mvregrp', sh_len_g1_indices, sh_h_mapper, z_covs, z_sh_ind, Zbeta, VH_all, sigma2_v)
}

