# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib mvregrp
#' @importFrom Rcpp evalCpp
NULL

#' @export
generateSymmetricMatrix <- function(offDiagonal, n) {
    .Call('_mvregrp_generateSymmetricMatrix', PACKAGE = 'mvregrp', offDiagonal, n)
}

#' @export
my_dmvnorm <- function(x, Sigma) {
    .Call('_mvregrp_my_dmvnorm', PACKAGE = 'mvregrp', x, Sigma)
}

#' @export
calc_loglik <- function(sh_len_g1_indices, sh_h_mapper, z_sh_ind, Zbeta, VH_all, sigma2_v) {
    .Call('_mvregrp_calc_loglik', PACKAGE = 'mvregrp', sh_len_g1_indices, sh_h_mapper, z_sh_ind, Zbeta, VH_all, sigma2_v)
}

#' @export
update_VH_multi <- function(sh_len_g1_indices, hit_len, sh_h_mapper, z_sh_ind, Zbeta, VH_all, temp, sigma2_e_inv, sigma2_v_inv) {
    invisible(.Call('_mvregrp_update_VH_multi', PACKAGE = 'mvregrp', sh_len_g1_indices, hit_len, sh_h_mapper, z_sh_ind, Zbeta, VH_all, temp, sigma2_e_inv, sigma2_v_inv))
}

